name = "lean-clvm"
defaultTargets = ["Main"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.11.0"

[[lean_lib]]
name = "Clvm"

[[lean_lib]]
name = "Incubator"

[[lean_exe]]
name = "Main"
root = "Main"
